import sqlite3
import random
import string
import os
import sys

# Add the project root to the python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import adder, check_password, update_pss, delete_user, store_otp, verify_otp, get_user_by_identifier
from flask import Flask, request, redirect, url_for, session, render_template, render_template_string, send_from_directory, jsonify

# Path to the static export generated by Next.js
frontend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'ROOTS', 'out'))

app = Flask(__name__, 
            static_folder=frontend_dir, 
            static_url_path='')

# Keep this secret in a real application!
app.secret_key = 'super_secret_development_key'

# Dictionary mapping course IDs to external video URLs
COURSE_LINKS = {
    "red_teaming_101": "https://www.youtube.com/watch?v=example1", 
    "bug_bounty_basics": "https://www.youtube.com/watch?v=example2",
    "roblox_game_dev": "https://www.youtube.com/watch?v=example3"
}

# --- SPA Routing Helpers ---
@app.route('/')
def serve_index():
    if os.path.exists(os.path.join(app.static_folder, 'index.html')):
        return send_from_directory(app.static_folder, 'index.html')
    return "UI is building... please wait and refresh in a minute."

@app.route('/home')
@app.route('/dashboard')
@app.route('/path')
@app.route('/courses')
@app.route('/streak')
@app.route('/tree')
def serve_pages():
    path = request.path.strip('/')
    html_file = f"{path}.html"
    if os.path.exists(os.path.join(app.static_folder, html_file)):
        return send_from_directory(app.static_folder, html_file)
    # Fallback to index if subpage not found (for SPA behavior)
    return send_from_directory(app.static_folder, 'index.html')

# --- API Endpoints ---
@app.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    identifier = data.get('identifier')
    password = data.get('password')
    
    result = check_password(identifier, password)
    if result != "correct pass":
        name = get_user_by_identifier(identifier)
        if name:
            result = check_password(name, password)
            if result == "correct pass":
                session['user_name'] = name
                return jsonify({"status": "success", "message": "Login successful"})
        return jsonify({"status": "error", "message": result})
    
    session['user_name'] = identifier
    return jsonify({"status": "success", "message": "Login successful"})

@app.route('/signup', methods=['POST'])
def signup():
    data = request.get_json()
    name = data.get('name')
    email = data.get('email')
    password = data.get('password')
    number = data.get('number', '')
    
    result = adder(name, email, password, number)
    if result == "Inserted successfully!":
        session['user_name'] = name
        return jsonify({"status": "success", "message": "Signup successful"})
    else:
        return jsonify({"status": "error", "message": result})

@app.route('/otp-request', methods=['POST'])
def otp_request_api():
    data = request.get_json()
    identifier = data.get('identifier')
    user_name = get_user_by_identifier(identifier)
    if user_name:
        otp = ''.join(random.choices(string.digits, k=6))
        if store_otp(identifier, otp):
            print(f"DEBUG: Sending OTP {otp} to {identifier}")
            session['otp_identifier'] = identifier
            return jsonify({"status": "success", "message": "OTP sent"})
        return jsonify({"status": "error", "message": "Error storing OTP"})
    return jsonify({"status": "error", "message": "User not found"})

@app.route('/otp-verify', methods=['POST'])
def otp_verify_api():
    data = request.get_json()
    otp = data.get('otp')
    identifier = session.get('otp_identifier')
    if not identifier:
        return jsonify({"status": "error", "message": "No OTP session active"})
    
    if verify_otp(identifier, otp):
        user_name = get_user_by_identifier(identifier)
        session['user_name'] = user_name
        session.pop('otp_identifier', None)
        return jsonify({"status": "success", "message": "OTP verified"})
    return jsonify({"status": "error", "message": "Invalid OTP"})

@app.route('/logout')
def logout():
    session.pop('user_name', None)
    return jsonify({"status": "success", "message": "Logged out"})

@app.route('/api/session')
def get_session():
    if 'user_name' in session:
        return jsonify({
            "status": "success", 
            "user": {
                "name": session['user_name'],
                "level": 14, 
                "xp": 12450,
                "maxXP": 15000
            }
        })
    return jsonify({"status": "error", "message": "Not logged in"}), 401

@app.route('/play/<course_id>')
def play_course(course_id):
    if course_id in COURSE_LINKS:
        return redirect(COURSE_LINKS[course_id])
    return "Course not found", 404

# Serve static assets (_next, etc.)
@app.route('/<path:filename>')
def serve_static(filename):
    return send_from_directory(app.static_folder, filename)

if __name__ == '__main__':
    app.run(debug=True, port=5000)
